# Generated by Django 3.2.16 on 2022-11-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_auto_20221121_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='stream_platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
